name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: [ self-hosted, windows, x64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore
        run: dotnet restore
        working-directory: src
      - name: Build
        run: dotnet publish Datapoint.sln --no-restore
        working-directory: src
      - name: Pack
        run: dotnet pack Datapoint.sln -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --no-build --no-restore --output ../dist 
        working-directory: src
      - name: Push
        run: dotnet nuget push -s http://nuget.datapoint.software/v3/index.json *.nupkg --api-key=${{secrets.DATAPOINT_NUGET_API_KEY}}
        working-directory: dist

